"""OptaExpert — Opta/TheAnalyst win probability predictions.

Uses pre-fetched Opta predictions stored in the predictions table
(model_version='opta_analyst'). These combine betting market odds
with Opta Power Rankings and are generated by simulating fixtures
thousands of times.

When Opta predictions are available, this is one of the strongest
signals because it represents a well-funded, professionally maintained
model with access to proprietary data.
"""
from __future__ import annotations

import numpy as np
import pandas as pd

from footy.models.experts._base import Expert, ExpertResult, _norm3


class OptaExpert(Expert):
    """Use Opta/TheAnalyst predictions as expert signal."""

    name = "opta"

    def __init__(self):
        self._opta_cache: dict[int, tuple[float, float, float]] = {}
        self._loaded = False

    def _load_opta(self):
        """Load Opta predictions from DB into cache."""
        if self._loaded:
            return
        try:
            from footy.db import connect
            con = connect()
            rows = con.execute("""
                SELECT match_id, p_home, p_draw, p_away
                FROM predictions
                WHERE model_version = 'opta_analyst'
                  AND p_home IS NOT NULL
            """).fetchall()
            for mid, ph, pd, pa in rows:
                self._opta_cache[int(mid)] = (float(ph), float(pd), float(pa))
        except Exception:
            pass
        self._loaded = True

    def compute(self, df: pd.DataFrame) -> ExpertResult:
        n = len(df)
        probs = np.full((n, 3), 1.0 / 3.0)
        conf = np.zeros(n)

        opta_ph = np.zeros(n)
        opta_pd = np.zeros(n)
        opta_pa = np.zeros(n)
        opta_has = np.zeros(n)
        opta_confidence_signal = np.zeros(n)

        self._load_opta()

        has_mid = "match_id" in df.columns

        for i, r in enumerate(df.itertuples(index=False)):
            if not has_mid:
                continue

            mid = getattr(r, "match_id", None)
            if mid is None:
                continue

            opta = self._opta_cache.get(int(mid))
            if opta is None:
                continue

            ph, pd_, pa = opta
            if ph > 0 and pd_ > 0 and pa > 0:
                probs[i] = _norm3(ph, pd_, pa)
                opta_ph[i] = ph
                opta_pd[i] = pd_
                opta_pa[i] = pa
                opta_has[i] = 1.0
                # Opta confidence: how decisive is the prediction?
                opta_confidence_signal[i] = max(ph, pd_, pa) - min(ph, pd_, pa)
                conf[i] = 0.85  # Opta predictions are high quality when available

        return ExpertResult(
            probs=probs,
            confidence=conf,
            features={
                "opta_ph": opta_ph,
                "opta_pd": opta_pd,
                "opta_pa": opta_pa,
                "opta_has": opta_has,
                "opta_confidence": opta_confidence_signal,
            },
        )
